/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_0bdba248 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/faqelofxvlhfuoulcosc/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";
import { cache } from "./cache.tsx";

// Reuse a single client instance instead of creating new ones
let _client: ReturnType<typeof createClient> | null = null;

const client = () => {
  if (!_client) {
    _client = createClient(
      Deno.env.get("SUPABASE_URL") ?? '',
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ''
    );
  }
  return _client;
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0bdba248").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
  // Update cache
  cache.set(key, value, 5 * 60 * 1000);
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  // Check cache first
  const cached = cache.get(key);
  if (cached !== null) {
    return cached;
  }
  
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_0bdba248").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  
  const value = data?.value;
  // Cache for 5 minutes
  if (value !== undefined && value !== null) {
    cache.set(key, value, 5 * 60 * 1000);
  }
  return value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0bdba248").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
  // Remove from cache
  cache.delete(key);
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0bdba248").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_0bdba248").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0bdba248").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  // Check cache first (cache key includes prefix)
  const cacheKey = `prefix:${prefix}`;
  const cached = cache.get<any[]>(cacheKey);
  if (cached !== null) {
    return cached;
  }
  
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_0bdba248").select("key, value").like("key", prefix + "%");
  if (error) {
    console.error(`[KV Store] getByPrefix error:`, {
      code: error.code,
      message: error.message,
      details: error.details,
      hint: error.hint
    });
    return [];
  }
  
  const values = data?.map((d) => d.value) ?? [];
  // Cache for 2 minutes (prefix queries change more frequently)
  cache.set(cacheKey, values, 2 * 60 * 1000);
  return values;
};